<a href="https://colab.research.google.com/github/Saraldedv/CCDEPLRL_EXERCISES/blob/main/Exercise6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 6

In [15]:
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [16]:
import numpy as np
import pandas as pd

path = "https://github.com/robitussin/CCDEPLRL_EXERCISES/blob/9b8ac1c5683abecc144f0af47eb7cda0688e12b7/dataset/reviews.json?raw=true"

dataset = pd.read_json(path)

In [17]:
dataset.head(20)

review  rating
0                     sir okay armygreen shorts nice        5
1   di pareha yong mga size nila may sobrang liit ...       5
2   super worth it ang ganda Sombra grabi order na...       5
3                                    ganda po salamat       5
4                 maayos pagkadeliver maganda den sya       5
5   ang gnda nang short nagustohan nang binigyan k...       4
6              maganda sya medyo manipis nga lang ..        4
7                                                           4
8                                                           4
9   manipis pla at ska dami himulmol ng sinulid, d...       2
10                                     madali maponit       2
11            Unsatisfied. Poor quality. easily torn.       1
12  Thank You ang Ganda niyaUmorder ulit ako ng 50...       5
13  Good quality at maayos naman ang pagkakabalot....       5
14  ganda niyatry lang oorder ulit. kala ko malapa...       5
15   GandaGanda GandagandaGandaGanda GandaGandaGanda        5
16  ang ganda superrrrr...makapit pa sa dingding k...       5
17  Ok naman yung bricks diko inexpect na malaki k...       4
18  I love the color.. I like it so much.. kaso so...       4
19                                         Satisfied        4

## 1. Tokenize the data

In [18]:
dataset['sentiment'] = dataset['rating'].apply(lambda rating : 1 if rating > 3 else 0)
sentences = dataset['review'].tolist()
labels = dataset['sentiment'].tolist()

# Separate out the sentences and labels into training and test sets
training_size = int(len(sentences) * 0.8)

training_sentences = sentences[0:training_size]
testing_sentences = sentences[training_size:]
training_labels = labels[0:training_size]
testing_labels = labels[training_size:]

# Make labels into numpy arrays for use with the network later
training_labels_final = np.array(training_labels)
testing_labels_final = np.array(testing_labels)

In [19]:

vocab_size = 3600
embedding_dim = 16
max_length = 100
trunc_type='post'
padding_type='post'
oov_tok = ""

In [20]:
# answer here

# Import the Tokenizer
tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(training_sentences)
padded = pad_sequences(sequences,maxlen=max_length, padding=padding_type,
                       truncating=trunc_type)

testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sequences,maxlen=max_length,
                               padding=padding_type, truncating=trunc_type)

## 2. Sequence the data

In [30]:
sequences = tokenizer.texts_to_sequences(sentences)
print (sequences)

[[749, 80, 1514, 390, 66], [42, 1515, 517, 63, 62, 219, 46, 89, 603, 1516], [94, 126, 11, 9, 55, 1517, 1518, 24, 3, 100, 42, 100, 1519, 1520, 55, 24, 167, 54, 14, 9, 168, 38], [55, 21, 104], [119, 1521, 23, 604, 22], [9, 1522, 345, 518, 1523, 345, 1524, 5, 104, 44, 6, 41, 605, 9, 1007, 180, 27, 15, 21, 220], [23, 22, 153, 127, 120, 12], [], [], [127, 445, 14, 750, 1008, 1525, 10, 1526, 42, 23, 9, 519, 42, 751, 1009, 91, 391, 91, 317, 1527, 520, 10, 1528], [606, 1529], [1530, 607, 47, 1531, 1532], [27, 15, 9, 55, 1533, 167, 54, 10, 1534, 35, 36, 272, 3, 114, 101, 521, 1010], [30, 47, 14, 119, 17, 9, 1535, 27, 15, 16], [55, 1536, 12, 392, 167, 446, 5, 1537, 33, 107, 28, 9, 55, 522, 752], [1538, 1539, 1540], [9, 55, 1541, 1542, 25, 6, 1011, 114, 25, 1543, 9, 1011, 77, 16, 14, 6, 1544, 169, 115, 24, 167, 523], [40, 17, 7, 1545, 608, 753, 3, 447, 253, 108, 12, 8, 127, 107, 22, 42, 393, 136, 6, 181, 195, 154, 524, 28, 40, 3, 22, 19, 2, 50, 108, 12, 17, 182, 609, 5, 12, 22, 10, 1546, 1547, 3]

## 3. Pad the data

In [21]:
# answer here


In [22]:


# Specify a max length for the padded sequences
padded = pad_sequences(sequences, maxlen=15)
print(padded)

[[   0    0    0 ... 1514  390   66]
 [   0    0    0 ...   89  603 1516]
 [  24    3  100 ...    9  168   38]
 ...
 [ 431   20 3131 ...  218  654   75]
 [   0    0    0 ...  159   38  444]
 [  35 1438    5 ...   87  464   12]]


## 4. Train a sentiment model

In [23]:
# answer here
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
    tf.keras.layers.GlobalAveragePooling1D(),  # Use Global Average Pooling
    tf.keras.layers.Dense(6, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.build(input_shape=(None, max_length))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 100, 16)        │        57,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_3      │ (None, 16)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 6)              │           102 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 57,709 (225.43 KB)

 Trainable params: 57,709 (225.43 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
num_epochs = 200
model.fit(padded, training_labels_final, epochs=num_epochs, validation_data=(testing_padded, testing_labels_final))

Epoch 1/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.6014 - loss: 0.6898 - val_accuracy: 0.2139 - val_loss: 0.7454
Epoch 2/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5891 - loss: 0.6779 - val_accuracy: 0.2139 - val_loss: 0.7579
Epoch 3/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6409 - loss: 0.6655 - val_accuracy: 0.2139 - val_loss: 0.7412
Epoch 4/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7016 - loss: 0.6435 - val_accuracy: 0.2139 - val_loss: 0.7507
Epoch 5/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7700 - loss: 0.6140 - val_accuracy: 0.2090 - val_loss: 0.7167
Epoch 6/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8336 - loss: 0.5786 - val_accuracy: 0.2637 - val_loss: 0.7027
Epoch 7/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8420 - loss: 0.5434 - val_accuracy: 0.5771 - val_loss: 0.6865
Epoch 8/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9119 - loss: 0.4920 - val_accuracy: 0.3532

## Get files for visualing the network

In [25]:
# answer here
e = model.layers[0]
weights = e.get_weights()[0]
print(weights.shape) # shape: (vocab_size, embedding_dim)

(3600, 16)


## 5. Predict sentiment with new reviews

In [36]:
fake_reviews = ['super tibay ng product na ito',
                'tangina ng quality ng product na ito',
                'pakyu bobo mo',
                'maayos at malinis ang item na nabili ko salamat seller',
                'mabagal mag reply ang seller tas low quality pa ang product',
                'tang ina sobra sarap',
                'Maganda product',
                'sakto lang']

print(fake_reviews)

# Create the sequences
padding_type = 'post'
sample_sequences = tokenizer.texts_to_sequences(fake_reviews)
fakes_padded = pad_sequences(sample_sequences, padding=padding_type, maxlen=max_length)

print('\nHOT OFF THE PRESS! HERE ARE SOME NEWLY MINTED, ABSOLUTELY GENUINE REVIEWS!\n')

# Predict sentiment
classes = model.predict(fakes_padded)

# Display each review with a human-readable sentiment
for i in range(len(fake_reviews)):
    # Using a threshold of 0.5 to decide sentiment (Sigmoid output between 0 and 1)
    sentiment = "Positive" if classes[i] >= 0.5 else "Negative"
    print(fake_reviews[i])
    print(f"Sentiment: {sentiment}")
    print(f"Model Output (Probability): {classes[i][0]:.4f}")
    print('\n')

['super tibay ng product na ito', 'tangina ng quality ng product na ito', 'pakyu bobo mo', 'maayos at malinis ang item na nabili ko salamat seller', 'mabagal mag reply ang seller tas low quality pa ang product', 'tang ina sobra sarap', 'Maganda product', 'sakto lang']

HOT OFF THE PRESS! HERE ARE SOME NEWLY MINTED, ABSOLUTELY GENUINE REVIEWS!

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
super tibay ng product na ito
Sentiment: Positive
Model Output (Probability): 0.5754


tangina ng quality ng product na ito
Sentiment: Negative
Model Output (Probability): 0.4696


pakyu bobo mo
Sentiment: Negative
Model Output (Probability): 0.4179


maayos at malinis ang item na nabili ko salamat seller
Sentiment: Negative
Model Output (Probability): 0.4368


mabagal mag reply ang seller tas low quality pa ang product
Sentiment: Negative
Model Output (Probability): 0.2664


tang ina sobra sarap
Sentiment: Negative
Model Output (Probability): 0.4109


Maganda product
Sentiment: Positive
Model Output (Probabi